<?php
/** @var \Avanti\BackToTop\Block\BackToTop $block */
/** @var \Magento\Framework\Escaper $escaper */

?>
<?php if ($block->isEnabled()): ?>

<a href="#"
  id="back-to-top"
  class="back-to-top <?= $escaper->escapeHtml($block->getPosition()) ?>"
  title="<?= $escaper->escapeHtml(__('Back to top')) ?>"
  style="background-color: <?= $escaper->escapeHtml($block->getColor()) ?>;">
   <svg width="12" height="13" viewBox="0 0 12 13" fill="none" xmlns="http://www.w3.org/2000/svg">
       <path d="M-2.85587e-07 5.5056L1.41855 6.93368L4.51649 3.83575L4.51649 12.0391L6.51891 12.0391L6.51891 3.83575L9.61685 6.93368L11.0354 5.5056L5.5177 0.000443217L-2.85587e-07 5.5056Z" fill="white"/>
   </svg>
</a>

<?php endif; ?>
