<div class="checkout-steps-wrapper">

    <ul class="checkout-steps">
        <li class="step-cart">
            <div class="step">1</div>
            <span><?= __('Cart') ?></span>
        </li>

        <li class="step-shipping">
            <div class="step">2</div>
            <span><?= __('Delivery') ?></span>
        </li>

        <li class="step-payment">
            <div class="step">3</div>
            <span><?= __('Payment') ?></span>
        </li>
    </ul>

    <div class="safe-purchase-message">
        <img src="<?= $block->getViewFileUrl('images/icons/verified-shield.svg'); ?>" alt="verified shield" />
        <span><?= __('100% Secure Purchase'); ?></span>
    </div>
</div>