<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * Promo header message template
 *
 * @var $block \Magento\Framework\View\Element\Template
 */
?>

<div class="flags-cards-wrapper">
    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/footer/cards-flags/amex.svg'); ?>" alt="amex" />
    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/footer/cards-flags/mastercard.svg'); ?>" alt="mastercard" />
    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/footer/cards-flags/visa.svg'); ?>" alt="visa" />
    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/footer/cards-flags/hypercard.svg'); ?>" alt="hypercard" />
    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/footer/cards-flags/elo.svg'); ?>" alt="elo" />
    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/footer/cards-flags/diners-club.svg'); ?>" alt="diners-club" />
    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/footer/cards-flags/paypay.svg'); ?>" alt="paypay" />
    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/footer/cards-flags/pix.svg'); ?>" alt="pix" />
    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/footer/cards-flags/boleto.svg'); ?>" alt="boleto" />
</div>